language: node_js
branches:
  except:
    - gh-pages
script:
  - commitlint-travis
  - yarn test
  - yarn build
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: public
  fqdn: patientaider.org
  on:
    branch: master
